Checkouts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# urlpatterns = [
#     path('checkout/<int:course_id>', views.Checkout, name='checkout'),
#     path('payment-success/<int:course_id>/',
#          views.PaymentSuccessful, name='payment-success'),
#     path('payment-failed/<int:course_id>/',
#          views.PaymentFailed, name='payment-failed'),
# ]

urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('payment_ipn/', views.payment_ipn, name='payment_ipn'),
    path('payment_return/', views.payment_return, name='payment_return'),
    path('invoice/<int:order_id>/', views.invoice, name='invoice'),
    path('query/', views.query, name='query'),
]

Gym/urls.py
from django import views
from django.conf import settings
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter
# from .views import ScheduleViewSet, ReviewViewSet, ChatMessageViewSet, NotificationViewSet, PaymentViewSet

router = DefaultRouter()
# router.register(r'schedules', ScheduleViewSet, basename='schedule')
# router.register(r'reviews', ReviewViewSet, basename='review')
# router.register(r'chat_messages', ChatMessageViewSet, basename='chat_message')
# router.register(r'notifications', NotificationViewSet, basename='notification')
# router.register(r'payments', PaymentViewSet, basename='payment')

urlpatterns = [
    path('', views.home, name="home"),
    path('', include(router.urls)),
    path('notification', views.notification, name='notification'),
    path('search', views.search, name='search'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webphongtapgym/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from Gym.consumers import NotificationConsumer
from Gym.views import home
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('', home, name="home"),
    path('', include('Gym.urls')),
    path('', include('Users.urls')),
    path('', include('Checkouts.urls')),
    path('', include('Carts.urls')),
    # path('api/', include('Users.urls')),
    # path('api/', include('Gym.urls')),
    path('api/', include('Courses.urls')),
]
websocket_urlpatterns = [
    path('ws/notification/', NotificationConsumer.as_asgi()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Courses/models.py
import logging
from django.db import models
from Users.models import CustomUser, TrainerProfile
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator


class Category(models.Model):  # lớp phân loại
    category_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:  # lớp định nghĩa chữ
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name


class Course(models.Model):
    SCHEDULE_CHOICES = [
        ('thu 2', 'Thứ 2'),
        ('thu 3', 'Thứ 3'),
        ('thu 4', 'Thứ 4'),
        ('thu 5', 'Thứ 5'),
        ('thu 6', 'Thứ 6'),
        ('thu 7', 'Thứ 7'),
        ('chunhat', 'Chủ nhật'),
    ]
    TIME_CHOICES = [
        ('08:00 - 09:00', '08:00 - 09:00'),
        ('09:00 - 10:00', '09:00 - 10:00'),
        ('10:00 - 11:00', '10:00 - 11:00'),
        ('13:30 - 14:30', '13:30 - 14:30'),
        ('14:00 - 15:00', '14:00 - 15:00'),
        ('15:00 - 16:00', '15:00 - 16:00'),
        ('16:00 - 17:00', '16:00 - 17:00'),
        ('17:00 - 18:00', '17:00 - 18:00'),
        ('18:30 - 19:30', '18:30 - 19:30'),
        ('19:00 - 20:00', '19:00 - 20:00'),
        ('20:00 - 21:00', '20:00 - 21:00'),
        ('21:00 - 22:00', '21:00 - 22:00'),
    ]
    DURATION_CHOICES = [
        ('1thang', '1 tháng'),
        ('2thang', '2 tháng'),
        ('3thang', '3 tháng'),
        ('6thang', '6 tháng'),
    ]
    address_course_choices = [
        ('phong101', 'phòng 101'),
        ('phong102', 'phòng 102'),
        ('phong103', 'phòng 103'),
        ('phong104', 'phòng 104'),
        ('phong105', 'phòng 105'),
        ('phong106', 'phòng 106'),
        ('phong107', 'phòng 107'),
        ('phong108', 'phòng 108'),
        ('phong109', 'phòng 109'),
        ('phong110', 'phòng 110'),
    ]

    id_course = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)  # Tên khoá học
    slug = models.SlugField(max_length=200, unique=True, default='')
    trainer = models.ForeignKey(TrainerProfile, on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE)
    image_course = models.ImageField(
        upload_to='course_images/', blank=True, null=True)
    banner_course = models.ImageField(
        upload_to='course_banners/', blank=True, null=True)
    address_course = models.CharField(
        max_length=30, choices=address_course_choices, default='phong101')
    schedule_course = models.CharField(
        max_length=30, choices=SCHEDULE_CHOICES, default='thu 2')
    time_course = models.CharField(
        max_length=50, choices=TIME_CHOICES, default='08:00 - 09:00')
    duration_course = models.CharField(
        max_length=30, choices=DURATION_CHOICES, default='1thang')
    description_course = models.TextField(
        max_length=500, blank=True, null=True)
    tuition_course = models.DecimalField(
        max_digits=10, decimal_places=0, default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    quantity_member = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_schedule_display(self):
        return dict(self.SCHEDULE_CHOICES).get(self.schedule_course, '')

    def get_duration_display(self):
        return dict(self.DURATION_CHOICES).get(self.duration_course, '')

    @property
    def ImageURL(self):
        try:
            url = self.image_course.url
        except:
            url = ''
        return url

    @property
    def BannerURL(self):
        try:
            url = self.banner_course.url
        except:
            url = ''
        return url


class Membership(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_joined = models.DateTimeField(auto_now_add=True)
    duration = models.CharField(
        _('Duration'), max_length=40, choices=Course.DURATION_CHOICES)
    schedule = models.CharField(
        _('Schedule'), max_length=40, choices=Course.SCHEDULE_CHOICES)
    time = models.CharField(
        _('Time'), max_length=40, choices=Course.TIME_CHOICES)

    def __str__(self):
        return f'{self.user.email} - {self.course.name}'


class Review(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    rating = models.IntegerField(default=0, validators=[
        MinValueValidator(1),
        MaxValueValidator(5)
    ])
    review_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email} - {self.course.name}'

Checkouts/views.py
from django.shortcuts import get_object_or_404

from .models import Checkout
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from Carts.models import CartItem
from Checkouts.models import Checkout
from Courses.models import Course, Membership
from datetime import datetime
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils.http import quote
from django.db.models import Sum
from Checkouts.forms import PaymentForm
from Checkouts.vnpay import vnpay
from Users.models import CustomUser
import hashlib
import hmac
import json
import urllib
import urllib.parse
import urllib.request
import random
import requests

from Courses.views import course_detail


def hmacsha512(key, data):
    byteKey = key.encode('utf-8')
    byteData = data.encode('utf-8')
    return hmac.new(byteKey, byteData, hashlib.sha512).hexdigest()


def payment(request):
    cart_items = CartItem.objects.filter(
        cart_id=request.user.id, is_active=True)
    total_price = 0
    for cart_item in cart_items:
        cart_item.tuition_course = cart_item.courses.tuition_course
        total_price += cart_item.tuition_course
        cart_item.name = cart_item.courses.name
    cart_id = request.user.id
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            order_type = form.cleaned_data['order_type']
            order_id = form.cleaned_data['order_id']
            amount = total_price
            order_desc = cart_id
            bank_code = form.cleaned_data['bank_code']
            language = form.cleaned_data['language']
            ipaddr = get_client_ip(request)

            vnp = vnpay()
            vnp.requestData['vnp_Version'] = '2.1.0'
            vnp.requestData['vnp_Command'] = 'pay'
            vnp.requestData['vnp_TmnCode'] = settings.VNPAY_TMN_CODE
            vnp.requestData['vnp_Amount'] = amount * 100
            vnp.requestData['vnp_CurrCode'] = 'VND'
            vnp.requestData['vnp_TxnRef'] = order_id
            vnp.requestData['vnp_OrderInfo'] = order_desc
            vnp.requestData['vnp_OrderType'] = order_type
            if language and language != '':
                vnp.requestData['vnp_Locale'] = language
            else:
                vnp.requestData['vnp_Locale'] = 'vn'

            if bank_code and bank_code != "":
                vnp.requestData['vnp_BankCode'] = bank_code

            vnp.requestData['vnp_CreateDate'] = datetime.now().strftime(
                '%Y%m%d%H%M%S')
            vnp.requestData['vnp_IpAddr'] = ipaddr
            vnp.requestData['vnp_ReturnUrl'] = settings.VNPAY_RETURN_URL
            vnpay_payment_url = vnp.get_payment_url(
                settings.VNPAY_PAYMENT_URL, settings.VNPAY_HASH_SECRET_KEY)
            print(vnpay_payment_url)
            return redirect(vnpay_payment_url)
        else:
            print("Dữ liệu biểu mẫu không hợp lệ")
    else:
        return render(request, "payment.html", {
            'cart_items': cart_items,
            'total_price': total_price,
            'title': "Thanh toán"
        })


def payment_ipn(request):
    inputData = request.GET
    if inputData:
        vnp = vnpay()
        vnp.responseData = inputData.dict()
        order_id = inputData['vnp_TxnRef']
        amount = inputData['vnp_Amount']
        order_desc = inputData['vnp_OrderInfo']
        vnp_TransactionNo = inputData['vnp_TransactionNo']
        vnp_ResponseCode = inputData['vnp_ResponseCode']
        vnp_TmnCode = inputData['vnp_TmnCode']
        vnp_PayDate = inputData['vnp_PayDate']
        vnp_BankCode = inputData['vnp_BankCode']
        vnp_CardType = inputData['vnp_CardType']
        vnp_TxnRef = inputData['vnp_TxnRef']
        vnp_SecureHash = inputData['vnp_SecureHash']
        vnp_BankTranNo = inputData['vnp_BankTranNo']
        vnp_TransactionStatus = inputData['vnp_TransactionStatus']
        if vnp.validate_response(settings.VNPAY_HASH_SECRET_KEY):
            # Check & Update Order Status in your Database
            # Your code here
            firstTimeUpdate = True
            totalamount = True
            if totalamount:
                if firstTimeUpdate:
                    if vnp_ResponseCode == '00':
                        print('Payment Success. Your code implement here')
                    else:
                        print('Payment Error. Your code implement here')

                    # Return VNPAY: Merchant update success
                    result = JsonResponse(
                        {'RspCode': '00', 'Message': 'Confirm Success'})
                else:
                    # Already Update
                    result = JsonResponse(
                        {'RspCode': '02', 'Message': 'Order Already Update'})
            else:
                # invalid amount
                result = JsonResponse(
                    {'RspCode': '04', 'Message': 'invalid amount'})
        else:
            # Invalid Signature
            result = JsonResponse(
                {'RspCode': '97', 'Message': 'Invalid Signature'})
    else:
        result = JsonResponse({'RspCode': '99', 'Message': 'Invalid request'})

    return result


def payment_return(request):
    inputData = request.GET
    if inputData:
        vnp = vnpay()
        vnp.responseData = inputData.dict()
        order_id = inputData['vnp_TxnRef']
        amount = int(inputData['vnp_Amount']) / 100
        order_desc = inputData['vnp_OrderInfo']
        vnp_TransactionNo = inputData['vnp_TransactionNo']
        vnp_ResponseCode = inputData['vnp_ResponseCode']
        vnp_TmnCode = inputData['vnp_TmnCode']
        vnp_PayDate = inputData['vnp_PayDate']
        vnp_BankCode = inputData['vnp_BankCode']
        vnp_CardType = inputData['vnp_CardType']
        vnp_TxnRef = inputData['vnp_TxnRef']
        vnp_SecureHash = inputData['vnp_SecureHash']
        vnp_BankTranNo = inputData['vnp_BankTranNo']
        vnp_TransactionStatus = inputData['vnp_TransactionStatus']
        if vnp.validate_response(settings.VNPAY_HASH_SECRET_KEY):
            if vnp_ResponseCode == "00":
                # Lấy thông tin từ cart_id
                cart_id = order_desc
                cart_items = CartItem.objects.filter(
                    cart_id=cart_id, is_active=True)

                # Tạo danh sách tên sản phẩm từ giỏ hàng
                course_names = [
                    cart_item.courses.name for cart_item in cart_items]
                # Thêm thông tin vào cơ sở dữ liệu
                Checkout.objects.create(
                    order_id=order_id,
                    checkout_Amount=amount,
                    user_id=cart_id,
                    status='cho_xac_nhan',
                    checkout_Coursename=', '.join(course_names),
                )
                for cart_item in cart_items:
                    course = cart_item.courses
                    course.quantity_member -= 1
                    course.save()

                # Xoá các sản phẩm trong giỏ hàng
                cart_items.delete()
                return render(request, "payment_return.html", {"title": "Kết quả thanh toán",
                                                               "result": "Thành công", "order_id": order_id,
                                                               "amount": amount,
                                                               "order_desc": order_desc,
                                                               "vnp_TransactionNo": vnp_TransactionNo,
                                                               "vnp_ResponseCode": vnp_ResponseCode,
                                                               }
                              )
            else:
                return render(request, "payment_return.html", {"title": "Kết quả thanh toán",
                                                               "result": "Lỗi", "order_id": order_id,
                                                               "amount": amount,
                                                               "order_desc": order_desc,
                                                               "vnp_TransactionNo": vnp_TransactionNo,
                                                               "vnp_ResponseCode": vnp_ResponseCode})
        else:
            return render(request, "payment_return.html",
                          {"title": "Kết quả thanh toán", "result": "Lỗi", "order_id": order_id, "amount": amount,
                           "order_desc": order_desc, "vnp_TransactionNo": vnp_TransactionNo,
                           "vnp_ResponseCode": vnp_ResponseCode, "msg": "Sai checksum"})
    else:
        return render(request, "payment_return.html", {"title": "Kết quả thanh toán", "result": ""})


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


n = random.randint(10**11, 10**12 - 1)
n_str = str(n)
while len(n_str) < 12:
    n_str = '0' + n_str


def query(request):
    if request.method == 'GET':
        return render(request, "query.html", {"title": "Kiểm tra kết quả giao dịch"})

    url = settings.VNPAY_API_URL
    secret_key = settings.VNPAY_HASH_SECRET_KEY
    vnp_TmnCode = settings.VNPAY_TMN_CODE
    vnp_Version = '2.1.0'

    vnp_RequestId = n_str
    vnp_Command = 'querydr'
    vnp_TxnRef = request.POST['order_id']
    vnp_OrderInfo = 'kiem tra gd'
    vnp_TransactionDate = request.POST['trans_date']
    vnp_CreateDate = datetime.now().strftime('%Y%m%d%H%M%S')
    vnp_IpAddr = get_client_ip(request)

    hash_data = "|".join([
        vnp_RequestId, vnp_Version, vnp_Command, vnp_TmnCode,
        vnp_TxnRef, vnp_TransactionDate, vnp_CreateDate,
        vnp_IpAddr, vnp_OrderInfo
    ])

Checkouts/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="VNPAY PAYMENT GATEWAY DEMO">
    <meta name="author" content="VNPAY">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="{% static "css/jumbotron-narrow.css" %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!--[if lt IE 9]><script src="{% static "js/ie8-responsive-file-warning.js" %}"></script><![endif]-->
    <script src="{% static "js/ie-emulation-modes-warning.js" %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
</head>
<body>
<div class="container">
    <div class="header clearfix">
       {% comment %} <nav>
            <ul class="nav nav-pills pull-right">
                <li role="presentation"><a href="/">Danh sách</a></li>
                <li role="presentation" class="active"><a href="/CreateOrder">Tạo mới</a></li>

            </ul>
        </nav>{% endcomment %}
    </div>
    {% block content %}
    {% endblock %}
    <footer class="footer">
        <p>&copy; ThanhVix {% now "Y" %}</p>
    </footer>
</div> <!-- /container -->


<link href="https://pay.vnpay.vn/lib/vnpay/vnpay.css" rel="stylesheet"/>
<script src="https://pay.vnpay.vn/lib/vnpay/vnpay.js"></script>

<script type="text/javascript">
    $("#btnPopup").click(function () {
        var postData = $("#frmCreateOrder").serialize();
        var submitUrl = $("#frmCreateOrder").attr("action");
        $.ajax({
            type: "POST",
            url: submitUrl,
            data: postData,
            dataType: 'JSON',
            success: function (x) {
                if (x.code === '00') {
                    vnpay.open({width: 480, height: 600, url: x.data});
                    return false;
                } else {
                    alert(x.Message);
                }
            }
        });
        return false;
    });
</script>


<script>

</script>
</body>
</html>

Checkouts/templates/checkout.html
{% extends 'base.html' %}{% load static %}
{% block checkout %}
<section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-10">
          <a class="btn btn-outline-primary mt-3 mb-3" href="{% url 'home' %}"
          style="border-radius: 5px">&#x2190; Tiếp Tục Mua Khoá Học</a>
          <div class="card rounded-3 mb-4">
            <div class="card-body p-4">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                  <img
                    src="{{course.ImageURL}}"
                    class="img-fluid rounded-3" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3">
                  <p class="lead fw-normal mb-2">{{course.name}}</p>
                  <p><span class="text-muted">Lịch tập: </span>{{course.get_time_display}} {{course.get_schedule_display}}</span></p>
                  <span class="text-muted">Thời gian: </span>{{course.get_duration_display}}  </span>
  
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                  <h5 class="mb-0">{{course.tuition_course | floatformat:0}} VNĐ</h5>
                </div>
              </div>
            </div>
          </div>
          <div class="card mb-4">
            <div class="card-body p-4 d-flex flex-row">
              <span class="text-muted">Tổng Số Tiền: </span>{{course.tuition_course | floatformat:0}} VNĐ </span>
            </div>
          </div>
          <div class="card">
            <div class="card-body">  
                {{paypal.render}}
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </section>
{% endblock checkout %}

Checkouts/templates/invoice.html
{% extends "base_layout.html" %}
{% block content %}
<div class="row" style="height: 74px"></div>
<div class="container-fluid">
    <div id="ui-view" data-select2-id="ui-view">
        <div>
            <div class="card">
                <div class="card-header">Số hóa đơn: 
                    <strong>{{ checkout.order_id }}</strong>
                </div>
                <div class="card-header">Tên người mua:
                    <strong>{{user.first_name}} {{user.last_name}}</strong>
                <div class="card-body p-5 ">
                    <div class="table-responsive-sm">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Tên Khoá Học</th>
                                    <th class="center">Huấn Luyện Viên</th>
                                    <th class="right">Lịch Tập Luyện</th>
                                    <th class="right">Ngày Tạo</th>
                                    <th class="right">Số Tiền</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for course_info in course_info_list %}
                                <tr>
                                    <td>{{ course_info.name }}</td>
                                    <td class="center">{{ course_info.trainer }}</td>
                                    <td class="left">{{ course_info.time_course }} {{ course_info.schedule_course }}</td>
                                    <td class="center">{{ checkout.created_date }}</td>
                                    <td class="center">{{ course_info.tuition_course }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-5 ml-auto">
                            <table class="table table-clear">
                                <tbody>
                                    <tr>
                                        <td class="left">
                                            <strong>Tổng Cộng</strong>
                                        </td>
                                        <td class="right">
                                            <strong>{{ checkout.checkout_Amount }}</strong>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <a class="btn btn-sm btn-secondary float-right mr-1 d-print-none" href="#" onclick="javascript:window.print();" data-abc="true">
                            <i class="fa fa-print"></i> In hoá đơn
                            </a>
                            <a class="btn btn-sm btn-success float-right mr-1 d-print-none" href="{% url "course_purchased" %}">
                                &#x2190; Quay lại
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Checkouts/templates/payment.html
{% extends "base_layout.html" %}
{% block content %}
    <h1>Thanh toán Redirect</h1>
    <div class="table-responsive">
        <form action="{% url "payment"%}" id="create_form" method="post">
            <div class="form-group">
                <label for="order_type">Thanh Toán</label>
                <select name="order_type" id="order_type" class="form-control">
                    <option value="billpayment">Thanh toán hóa đơn</option>
                </select>
            </div>
            <div class="form-group">
                <label for="order_id">Mã hóa đơn</label>
                <input class="form-control" id="order_id"
                       name="order_id" type="text" value="{% now "YmdHis" %}" readonly/>
            </div>
            <div class="form-group">
                <label for="amount">Số tiền</label>
                <input class="form-control" id="amount"
                       name="amount" type="number" value="{{total_price}}" placeholder="" readonly/>
            </div>
            <div class="form-group">
                <label for="order_desc">Nội dung đơn hàng</label>
                <textarea class="form-control" cols="10" id="order_desc" name="order_desc" rows="1" readonly>Thanh toan don hang thoi gian: {% now "Y-m-d H:i:s" %}</textarea>
            </div>
            <div class="form-group">
                <label for="bank_code">Ngân hàng</label>
                <select name="bank_code" id="bank_code" class="form-control">
                    <option value="NCB"> Ngan hang NCB</option>
                </select>
            </div>
            <div class="form-group">
                <label for="language">Ngôn ngữ</label>
                <select name="language" id="language" class="form-control">
                    <option value="vn">Tiếng Việt</option>
                    <option value="en">English</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary py-3 px-4">Thanh toán VNPay</button>
            {% csrf_token %}
            <div class="form-group"></div>
        </form>
    </div>
{% endblock %}

Checkouts/templates/payment_return.html
{% extends "base_layout.html" %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading"><h2>{{ title }}: {{ result }}</h2></div>
        <div class="panel-body">
            <p>order_id:{{ order_id }}</p>
            <p>Số Tiền:{{ amount }}</p>
            <p>Mã Giỏ hàng:{{ order_desc }}</p>
            <p>vnp_TransactionNo:{{ vnp_TransactionNo }}</p>
            {% if vnp_ResponseCode == '00' %}
                <p>vnp_ResponseCode: {{ vnp_ResponseCode }} - Thành công</p>
            {% else %}
                <p>vnp_ResponseCode: {{ vnp_ResponseCode }} - Lỗi</p>
            {% endif %}
            {% if msg %}
                <p class="alert-warning"> {{ msg }}</p>
            {% endif %}
            <a class="btn btn-submit" href="{% url 'home' %}">&#x2190; Quay về Trang Chủ</a>

        </div>
    </div>
{% endblock %}

Checkouts/templates/query.html
{% extends "base_layout.html" %}
{% block content %}

    <h3>{{ title }}</h3>
    <div class="table-responsive">
        <form action="{% url "query" %}" id="create_form" method="post">

            <div class="form-group">
                <label for="order_id">Mã hóa đơn</label>
                <input class="form-control" id="order_id"
                       name="order_id" type="text"/>
            </div>
            <div class="form-group">
                <label for="order_id">Thời gian thanh toán</label>
                <input class="form-control" id="trans_date"
                       name="trans_date" type="text"/>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Query</button>
            </div>

            {% csrf_token %}
        </form>
        {% if response_json %}
            {% for key,val in response_json.items %}
             <div class="form-group">
                <label>{{ key }} : {{ val }}</label>
            </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}